services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
